<?php require '../tpe/app/templates/Layout/header.phtml'; ?>

<div>
    <?php if ($cliente): ?>
        <ul>
            <li>Nombre: <?= htmlspecialchars($cliente->nombre) ?> </li>
            <li>Teléfono: <?= htmlspecialchars($cliente->telefono) ?> </li>
            <li>DNI: <?= htmlspecialchars($cliente->dni) ?> </li>
            <li>Mail: <?= htmlspecialchars($cliente->mail) ?> </li>
            <li>Fecha de nacimiento: <?= htmlspecialchars($cliente->fecha_nacimiento) ?> </li>
            <li>Imagen: <img src="<?= htmlspecialchars($cliente->image) ?>" alt="Imagen del cliente" /></li>
        </ul>
    <?php else: ?>
        <p>No hay información del cliente disponible.</p>
    <?php endif; ?>
</div>

<?php require '../tpe/app/templates/Layout/footer.phtml'; ?>
