<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nuevo cliente</title>
</head>

<body>
    <h1>Editar venta:</h1>
    <?php if($clientes && $venta):?>
    <form action="" method="POST">
        <label for="clave_foranea">Selecciona el cliente:</label>
            <select name="clave_foranea" id="clave_foranea" required>
                <?php foreach ($clientes as $cliente): ?>
                    <option value="<?= $cliente->id_cliente ?>"> <?php echo $cliente->nombre ?> </option>
                <?php endforeach; ?>
            </select>
            <label for="monto">Monto:</label>
            <input type="number" name="monto" id="monto" value="<?php echo $venta->monto ?>"required>
            <label for="producto">Nombre del producto:</label>
            <input type="text" name="producto" id="producto" value="<?php echo $venta->producto ?>" required>
            <label for="importado">Importado:</label>
            <select name="importado" id="importado" value="<?php echo $venta->importado?>" required>
                <option value="1">Sí</option>
                <option value="0">No</option>
            </select>
            <label for="fecha_compra">Fecha de compra:</label>
            <input type="text" name="fecha_compra" id="fecha_compra" value="<?php echo $venta->fecha_compra ?>" required>
            <input type="submit" value="editar">
    </form>
    <?php endif;?>
</body>

</html>

<?php require '../tpe/app/plantillas/disenio/pieDePagina.phtml'; ?>

           

            

            
            


            