<?php
$sesionIniciada = isset($_SESSION['nombre']);
$current_page = basename($_SERVER['REQUEST_URI'], ".php");
?>

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PerfumeriasTandil</title>
    <link rel="stylesheet" type="text/css" href="css/estilos.css">
</head>

<body>
    <header>
        <p> PERFUMERIAS TANDIL</p>

        <?php if ($current_page != 'clientes'): ?>
            <a href="clientes">Clientes</a>
        <?php endif; ?>

        <?php if ($current_page != 'ventas'): ?>
            <a href="ventas">Ventas</a>
        <?php endif; ?>

        <?php if ($sesionIniciada): ?>
            <a href="cerrarSesion">Cerrar sesión</a>
            <?php else: ?>
                <a href="inicioSesion">Iniciar sesión</a>
        <?php endif; ?>

    </header>
</body>

</html>