<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PerfumeriasTandil</title>
    <link rel="stylesheet" type="text/css" href="css/estilos.css">
</head>
<body>
        <footer>
            <div class=footer>
                <p>SAN MARTIN 240</p>
                <p>2494556489</p>
            </div>
    </footer>
</body>