<ul class="listas">
    <p>Compras realizadas:</p>
    <?php if (!empty($ventasCliente)): ?>
        <?php foreach ($ventasCliente as $venta): ?>
            <li>
                <p><?=$venta->producto; ?></p>
                 
            </li>
        <?php endforeach; ?>
    <?php else: ?>
        <li>No hay productos disponibles para este cliente.</li>
    <?php endif; ?>
</ul>

<?php require '../tpe/app/plantillas/disenio/pieDePagina.phtml'; ?>