<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nuevo cliente</title>
</head>
<body>
<h1>Editar cliente:</h1>
    <form action="agregarCategoria" method="POST">
       <label for="nombre">Nombre:</label>
       <input type="text" id="nombre" name="nombre" value="<?php echo htmlspecialchars($nombre, ENT_QUOTES, 'UTF-8'); ?>" placeholder="<?echo $this->$cliente->nombre?>">
       <label for="dni">DNI:</label>
       <input type="number" id="dni" name="dni" value="<?= isset($dni) ? htmlspecialchars($dni, ENT_QUOTES, 'UTF-8') : ''; ?>">
       <label for="telefono">Telefono:</label>
       <input type="number" id="telefono" name="telefono" value="<?= isset($telefono) ? htmlspecialchars($telefono, ENT_QUOTES, 'UTF-8') : ''; ?>">
       <label for="mail">Mail:</label>
       <input type="text" id="mail" name="mail" value="<?= isset($mail) ? htmlspecialchars($mail, ENT_QUOTES, 'UTF-8') : ''; ?>">
       <label for="fecha_nacimiento">Fecha de nacimiento:</label>
       <input type="date" id="fecha_nacimiento" name="fecha_nacimiento" value="<?= isset($fecha_nacimiento) ? htmlspecialchars($fecha_nacimiento, ENT_QUOTES, 'UTF-8') : ''; ?>">
       <label for="imagen">Imagen:</label>
       <input type="text" id="imagen" name="imagen" value="<?= isset($imagen) ? htmlspecialchars($imagen, ENT_QUOTES, 'UTF-8') : ''; ?>">
       <input type="submit" name="submit" value="editar">
    </form>
</body>
</html>

<?php require '../tpe/app/templates/Layout/footer.phtml'; ?>
