<?php require '../tpe/app/plantillas/disenio/encabezado.phtml'; ?>

<div>
    <?php if ($venta && $clientes): ?>
        <ul>
            <li>Fecha de compra: <?php echo htmlspecialchars($venta->fecha_compra); ?></li>
            <li>Cliente: 
                <?php 
                $id=$venta->clave_foranea; 
                foreach ($clientes as $cliente) 
                {if ($cliente->$id_cliente==$id){
                    echo htmlspecialchars($cliente->$nombre);
                }
                }?>
            </li>
            <li>Monto: <?php echo htmlspecialchars($venta->monto); ?></li>
            <li>Producto: <?php echo htmlspecialchars($venta->producto); ?></li>
            <li>
                <?php if (isset($venta->importado)): ?>
                    <p>Es importado</p>
                <?php else: ?>
                    <p>No es importado</p>
                <?php endif; ?>
            </li>
        </ul>
    <?php endif; ?>
</div>