<?php require '../tpe/app/plantillas/disenio/encabezado.phtml'; ?>
<ul class="listas">
    <?php
    if (!empty($clientes) && (is_array($clientes) || is_object($clientes))):
        foreach ($clientes as $cliente): ?>
            <li>
                <a href="./cliente/<?= $cliente->id_cliente ?>"><?= $cliente->nombre ?></a>
                <div class="actions">
                    <?php if (isset($_SESSION['nombre'])): ?>
                        <a href="./eliminarCliente/<?= $cliente->id_cliente ?>" type="button" class='button'>Borrar</a>
                        <a href="./editarCliente/<?= $cliente->id_cliente ?>" type="button" class='button'>Editar</a>
                    <?php endif; ?>
                </div>
            </li>
        <?php endforeach ?>
    <?php endif; ?>

</ul>