<?php require '../tpe/app/templates/Layout/header.phtml'; ?>

<div>
    <?php if ($venta): ?>
        <ul>
            <li>Fecha de compra: <?php echo ($venta->fecha_compra); ?></li>
            <li>Cliente:<?php echo htmlspecia
            <li>Monto: <?php echo htmlspecialchars($venta->monto); ?></li>
            <li>Producto: <?php echo htmlspecialchars($venta->producto); ?></li>
            <li>
            <?php if (isset($venta->importado)): ?>
                <p>Es importado</p>
                <?php else: ?>
                    <p>No es importado</p>
                <?php endif; ?>
            </li>
        </ul>
    <?php endif; ?>
</div>
