<?php require '../tpe/app/templates/Layout/header.phtml'; ?>

<div>
    <?php if ($venta): ?>
        <ul>
            <li>Fecha de compra: <?php echo $this->venta->fecha_compra;?> </li>
            <li>Monto: <?php echo $this->venta->monto; ?> </li>
            <li>Producto: <?php echo $this->venta->producto; ?> </li>
            <li>
                <?php if ($this->$venta->importado): ?>
                    <p>Es importado</p>
                <?php else: ?>
                    <p>No es importado</p>
                <?php endif; ?>
            </li>
        </ul>
    <?php endif; ?>
</div>

<?php require '../tpe/app/templates/Layout/footer.phtml'; ?>
