<?php session_start(); ?>

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>

<header>
    <p> PERFUMERIAS TANDIL</p>

    <?php if (!isset($_SESSION['nombre'])): ?>
        <a href="showIniciarSesion">Iniciar Sesion</a>
    <?php else: ?>
        <p>Bienvenido, <?= $_SESSION['nombre']; ?></p>
        <a href="cerrarSesion">Cerrar Sesion</a>
    <?php endif; ?>
</header>

<body>
   <a href="ventas">Ventas</a>
   <a href="categorias">Categorias</a>
    
</body>

</html>

<?php require '../tpe/app/templates/Layout/footer.phtml'; ?>
