<?php require '../tpe/app/templates/Layout/header.phtml'; ?>
<ul class="listas">
    <?php
    if (!empty($ventas) && (is_array($ventas) || is_object($ventas))):
        foreach ($ventas as $venta): ?>
            <li>
                <a href="venta/<?= $venta->id_venta ?>"><?= $venta->producto ?></a>
                <div class="actions">
                <?php if (isset($_SESSION['nombre'])): ?>
                    <a href="./eliminarVenta/<?= $venta->id_venta ?>" type="button" class='button'>Borrar</a>
                    <a href="./actualizarVenta/<?= $venta->id_venta ?>" type="button" class='button'>Editar</a>
                 <?php endif; ?>
                   
                </div>
            </li>
        <?php endforeach ?>
    <?php endif; ?>
</ul>