<ul class="listas">
    <?php
    if (!empty($ventasCategoria) && (is_array($ventasCategoria) || is_object($ventasCategoria))):
        foreach ($ventasCategoria as $venta): ?>
            <li>
                <a href="venta/<?= $venta->id_venta ?>"><?= $venta->producto ?></a>

            </li>
        <?php endforeach ?>
    <?php endif; ?>
</ul>
<?php require '../tpe/app/templates/Layout/footer.phtml'; ?>