<?php if ($error): ?>
    <div>
        <?= $error ?>
    </div>
<?php endif ?>

<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<header>
    <p> PERFUMERIAS TANDIL</p>

</header>

<body>
    <form action="inicioSesion" method="post">
        <label for="nombre">Ingrese su nombre:</label>
        <input type="text" id="nombre" name="nombre"  value="<?= isset($nombre) ? htmlspecialchars($nombre, ENT_QUOTES, 'UTF-8') : ''; ?>">
        <label for="contrasena">Ingrese su contraseña:</label>
        <input type="password" id="contrasena" name="contrasena" value="<?= isset($contrasena) ? htmlspecialchars($contrasena, ENT_QUOTES, 'UTF-8') : ''; ?>">
        <input type="submit" name="submit" value="enviar">
    </form>

</body>

</html>

